---
title: "HW_10"
author: "Jarrod Pelkofer"
date: "March 27, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## HW 20.1-1 a, b, c

```{r}
random <- c(.3039, .7914, .8543, .6902, .3004, .0383)

# a)unbiased coin
flips <- character()
for(i in  random){
  if(i <= .50){
    flips <- c(flips, "Heads")
  }
  else{
    flips <- c(flips, "Tails")
  }
}

# b) Pitcher 60% strikes, 40% balls
pitches <- character()
for(i in  random){
  if(i <= .60){
    pitches <- c(pitches, "Strike")
  }
  else{
    pitches <- c(pitches, "Ball")
  }
}

# c) traffic light Green 40%, Yellow 10%, Red 50%
lights <- character()
for(i in random){
  if(i <= .10){
    lights <- c(lights, 'yellow')
  }else if(i > .10 & i <=.50){
    lights <- c(lights, 'green')
  }else {
    lights <- c(lights, 'red')
  }
}

flips
pitches
lights

```

##HW 20.1-2 a, b
```{r}

#a)
rand <- c(.3004,.0383,.3883,.6052,.2231,.4250,.3729,.7983,.2340,.0082)

weather <- character()
yesterday <- 'clear'

for(r in rand){
  if(yesterday == 'clear' & r > .20){
    weather <- c(weather, 'clear')
    yesterday <- 'clear'
  }else if(yesterday == 'clear' & r <= .20){
    weather <- c(weather, 'rainy')
    yesterday <- 'rainy'
  }else if(yesterday == 'rainy' & r > .40){
    weather <- c(weather, 'rainy')
    yesterday <- 'rainy'
  }else if(yesterday == 'rainy' & r <= .40){
    weather <- c(weather, 'clear')
    yesterday <- 'clear'
  }
}

print("weather part a:")
weather

#b)
set.seed(33)
rand_b <- runif(10, 0, 1)

weather_b <- character()
yesterday_b <- 'clear'

for(b in rand_b){
  if(yesterday_b == 'clear' & b > .20){
    weather_b <- c(weather_b, 'clear')
    yesterday_b <- 'clear'
  }else if(yesterday_b == 'clear' & b <= .20){
    weather_b <- c(weather_b, 'rainy')
    yesterday_b <- 'rainy'
  }else if(yesterday_b == 'rainy' & b > .40){
    weather_b <- c(weather_b, 'rainy')
    yesterday_b <- 'rainy'
  }else if(yesterday_b == 'rainy' & b <= .40){
    weather_b <- c(weather_b, 'clear')
    yesterday_b <- 'clear'
  }
}

print("weather part b:")
weather_b
```

